### ISSUE TITLE
Support for 0x0.st

### ISSUE THREAD

**Issue by Still34** [SrS2225a/custom_uploader#4]
I could not figure out how to get the configuration to work with 0x0.st. I keep getting Bad Request instead.

**Comment by SrS2225a** [comment]
Can you export your uploader settings and share what it looks like so that I can further assist you? Custom Uploader actually has support for sharex uploaders, so if you export an sharex uploader and import into Custom Uploader, it should add the uploader for you

**Comment by SrS2225a** [comment]
Thanks, after doing some more investigation, it looks like it might be 0x0 itself blocking the upload from the app, and not an issue of your configuration. In your 0x0.st upload settings, in the "URL Error Response" field, can you add the text "$regex:.*$" (without quotes), save then try uploading again? This will get the error response from 0x0 and add it to the bad request

**Comment by Still34** [comment]
![image](https://github.com/SrS2225a/custom_uploader/assets/5843208/e0e27fc9-79bb-440c-bacd-a3e8b66f69c2)
🤔 Interesting response from the server

**Comment by SrS2225a** [comment]
Yeah, it is pretty wired which confirms what I thought. All the other file transfer sites I tested works just fine (including my own) and never ran into such a response. Of all the problem instances, they were related to a config issue. I have also sent an email to the site owner about the problem, and will keep you up to date on further updates. In the meantime, I suggest using another free host such as https://transfer.sh

**Comment by SrS2225a** [comment]
The website owner has already gotten back to me about the issue. Turns out the reason 0x0 is blocking you is because 0x0 blocks requests from certain user agents to prevent abuse and spam, which they say happened several times in the past. To be able to upload to 0x0, the app needs to use an meaningful user agent one, rather the the one supplied by the HTTP client library I use.

I am not sure if this will work, but for now, try adding an valid user agent string to the "upload headers" of your file host. I will have the user agent fix in the next version of my app, which will contain a number of enhancements and improvements, so look forward to that :)

**Comment by SrS2225a** [comment]
Hi, the user agent thing that Custom Uploader was having issues with, is now fixed. You should see the new version of F-Droid soon
